accent = "#D9B167"
cursor = "#DFC99F"
foreground = "#CAA560"
background = "#14100A"
selection_foreground = "#F3EDDD"
selection_background = "#4A3B22"

color0 = "#2A2318"
color1 = "#DA4F2B"
color2 = "#8A9A4E"
color3 = "#D9B167"
color4 = "#B87333"
color5 = "#A3798C"
color6 = "#6FA089"
color7 = "#DFC99F"
color8 = "#8A7A5C"
color9 = "#E85A38"
color10 = "#A9B665"
color11 = "#F3D493"
color12 = "#D08B4C"
color13 = "#B58A9F"
color14 = "#93BFA7"
color15 = "#F3EDDD"
