$color = rgba(20,16,10,1.0)
$inner_color = rgba(20,16,10,0.85)
$outer_color = rgba(217,177,103,1.0)
$font_color = rgba(223,201,159,1.0)
$check_color = rgba(47,181,100,1.0)

label {
    monitor =
    text = Wake up. We're here. Why are you shaking?
    font_family = Pelagiad
    font_size = 26
    color = rgba(202,165,96,1.0)
    position = 0, 140
    halign = center
    valign = center
}
